package com.example.demo.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseid
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.coursename
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    private String coursename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseid
     *
     * @return the value of course.courseid
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseid
     *
     * @param courseid the value for course.courseid
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.coursename
     *
     * @return the value of course.coursename
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.coursename
     *
     * @param coursename the value for course.coursename
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }
}