package com.example.demo.model;

import java.math.BigDecimal;

public class Stucourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuCourse.id
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuCourse.courseid
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuCourse.grade
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    private BigDecimal grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuCourse.id
     *
     * @return the value of stuCourse.id
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuCourse.id
     *
     * @param id the value for stuCourse.id
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuCourse.courseid
     *
     * @return the value of stuCourse.courseid
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuCourse.courseid
     *
     * @param courseid the value for stuCourse.courseid
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuCourse.grade
     *
     * @return the value of stuCourse.grade
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public BigDecimal getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuCourse.grade
     *
     * @param grade the value for stuCourse.grade
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }
}