package com.example.demo.mapper;

import com.example.demo.model.Myusers;
import java.util.List;

public interface MyusersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    int insert(Myusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    Myusers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    List<Myusers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myusers
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    int updateByPrimaryKey(Myusers record);
}