package com.example.demo.mapper;

import com.example.demo.model.Stucourse;
import java.util.List;

public interface StucourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuCourse
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    int insert(Stucourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuCourse
     *
     * @mbggenerated Mon Mar 12 20:06:28 CST 2018
     */
    List<Stucourse> selectAll();
}